[tool.poetry]
name = "dz-9-2"
version = "0.1.0"
description = ""
authors = ["Yauheni Lampe <spakv49@gmail.com>"]
readme = "README.md"
packages = [{include = "dz_9"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
